name: test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  GOOGLETEST_VERSION: "1.15.2"

jobs:
  ctest:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - ubuntu-latest
          - macos-13
          # Can't add macos-13-xlarge due to
          # https://github.com/zacharyburnett/setup-abseil-cpp/issues/4
          - macos-latest-large
          # Disable macos-latest-xlarge due to timouts:
          # https://github.com/google/s2geometry/issues/409
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30
    steps:
      - uses: zacharyburnett/setup-abseil-cpp@4189ecb9fcc7441ed7536774fb0a3f04d3cb779a # Not a release, but has #423 fix.
        with:
          cmake-build-args: "-DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON -DABSL_ENABLE_INSTALL=ON -DBUILD_TESTING=off -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
          abseil-version: "20250814.1"
      - name: retrieve googletest v${{ env.GOOGLETEST_VERSION }}
        run: |
          wget https://github.com/google/googletest/releases/download/v${{ env.GOOGLETEST_VERSION }}/googletest-${{ env.GOOGLETEST_VERSION }}.tar.gz
          tar -xzvf googletest-${{ env.GOOGLETEST_VERSION }}.tar.gz
          echo GOOGLETEST_ROOT=${{ runner.temp }}/googletest-${{ env.GOOGLETEST_VERSION }} >> $GITHUB_ENV
        working-directory: ${{ runner.temp }}
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - run: mkdir build
      - run: cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_PREFIX_PATH=/usr/local/ -DGOOGLETEST_ROOT=${{ env.GOOGLETEST_ROOT }} -DGOOGLETEST_VERSION=${{ env.GOOGLETEST_VERSION }} ..
        working-directory: build/
      - run: cmake --build . --parallel 45
        working-directory: build/
      - if: always()
        run: cmake --build . --parallel 45 --target=test
        env:
          CTEST_OUTPUT_ON_FAILURE: ON
          CTEST_PARALLEL_LEVEL: 45
        working-directory: build/
