name: test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  ctest:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - ubuntu-latest
          # `large` is x86-64 and `xlarge` is AArch64.
          # https://docs.github.com/en/actions/reference/runners/larger-runners#available-macos-larger-runners-and-labels
          - macos-14-large
          - macos-14-xlarge
          - macos-latest-large
          # macos-latest-xlarge may timeout.
          # https://github.com/google/s2geometry/issues/409
          - macos-latest-xlarge
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30
    steps:
      - uses: zacharyburnett/setup-abseil-cpp@5386866b5b554e420966aa7f31a477ad92f185d2 # Not a release, but has #423 fix.
        with:
          cmake-build-args: "-DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON -DABSL_ENABLE_INSTALL=ON -DBUILD_TESTING=off -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
          abseil-version: "20250814.1"
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: mkdir build
      - run: >
          cmake
          -DWITH_PYTHON=yes
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_PREFIX_PATH=/usr/local/
          ..
        working-directory: build/
      - run: cmake --build . --parallel 45
        working-directory: build/
      - if: always()
        run: cmake --build . --parallel 45 --target=test
        env:
          CTEST_OUTPUT_ON_FAILURE: ON
          CTEST_PARALLEL_LEVEL: 45
        working-directory: build/
